Endpoints
gluuck/api-test pull request #1
Opened 2021-05-03 18:12 UTC by gluuck

2021-05-04 06:52 UTC, alxekb requested changes
@gluuck nice try keep it going!

2021-05-04 06:52 UTC, alxekb commented on .rspec
> +--color
@gluuck Please add a newline here.

2021-05-04 06:52 UTC, alxekb commented on Gemfile
> +
@gluuck Please remove this line :)

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        params.fetch(:user,{}).permit(:name, :email,:password)
@gluuck `#require`

2021-05-04 06:52 UTC, alxekb commented on spec/controllers/users_controller_spec.rb
> +	let!(:user){User.new}
@gluuck 
- [ ] fix identation here
- [ ] add FActoryBot
- [ ] don't use `let!` if you call `user` somwhere in the test blocks
- [ ] testing controllers is deprecated use request test instead

2021-05-04 06:52 UTC, alxekb commented on spec/controllers/users_controller_spec.rb
> +end
@gluuck add a newline here please.

2021-05-04 06:52 UTC, alxekb commented on spec/factories/user.rb
> +end
@gluuck add a newline here please 😴

2021-05-04 06:52 UTC, alxekb commented on spec/models/user_model_spec.rb
> +  user=User.new(name: 'Vasya',email:'vasya@gmail.com',password:'123123')
@gluuck FactoryBot will hwlp you fo fix this issue

2021-05-04 06:52 UTC, alxekb commented on spec/models/user_model_spec.rb
> +end
👀

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
>          @users = User.all
@gluuck Please add pagination/search or limit to a reasonable const.

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        render json: @user
@gluuck 👀  is it actual edit?

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +          render json: @user.errors, status: :unprocessable_entity
@gluuck Please use standart JSON response schema formant otherwise FE team will kill you.

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +          render json: @user
@gluuck nice try! 😉

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        render json[:notice]='User was destroyed'
@gluuck Please add a fail case scenario or global error handling everywhere.

2021-05-04 06:52 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        render json: { success: true } if @user.value?(@user.password)
@gluuck I'm sorry I can't understand this part.

2021-05-04 08:50 UTC, gluuck commented on app/controllers/api/v1/users_controller.rb
> +        render json: @user
don`t sure, i thought endpoint edit must render something )

2021-05-04 09:05 UTC, gluuck commented on app/controllers/api/v1/users_controller.rb
> +        render json: { success: true } if @user.value?(@user.password)
is it my thoughts , how i can check for compliance email to password . First i find user by email . but  i`m not sure that my render json is true )) . I must return @user to render ? And  my       if @user.value?(@user.password)  is not right?

2021-05-07 11:18 UTC, alxekb requested changes

2021-05-07 11:18 UTC, alxekb commented on db/migrate/20210503035748_create_users.rb
>        t.string :password
Please remove password from here&

2021-05-07 11:18 UTC, alxekb commented on db/schema.rb
>      t.string "password"
And here :)

2021-05-07 11:18 UTC, alxekb commented on spec/controllers/users_controller_spec.rb
> +end
newlinw here please

2021-05-07 11:18 UTC, alxekb commented on spec/factories/user.rb
> +    email { 'vasya@gmail.com' }
Please use counter here

2021-05-07 11:34 UTC, gluuck commented on db/migrate/20210503035748_create_users.rb
>        t.string :password
ок

2021-05-12 17:33 UTC, alxekb approved these changes

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        if @user["password_digest"] == params[:password]
`@user` is not a Hash

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        if @user["password_digest"] == params[:password]
`@user` can be nil

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +          }, status: 404
We have no 'password matching feature' yet.

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +          "requests": @users}
`@users`  is an ActiveRecord relation. We have no valid JSON here&

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +      def new;end
We don't need this endpoing in API only application.

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
>        def edit; end
Same thing here.

2021-05-12 17:33 UTC, alxekb commented on app/controllers/api/v1/users_controller.rb
> +        if @user
```
if @user.update(user_params)
  render json: ....
```

2021-05-13 04:49 UTC, merged